In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
np.pad(a,(2,2),mode="constant",constant_values=(0,0))

array([0, 0, 1, 2, 3, 4, 0, 0])

In [5]:
a = [[1,2,3,4],
    [5,6,7,8]]
np.pad(a,((2,2),(2,2)),mode="constant",constant_values=(0,0))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 4, 0, 0],
       [0, 0, 5, 6, 7, 8, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
a = [[1,2,3,4],
    [5,6,7,8],
    [1,2,3,4]]
np.pad(a,((2,2),(2,2)),mode="constant",constant_values=(0,0))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 4, 0, 0],
       [0, 0, 5, 6, 7, 8, 0, 0],
       [0, 0, 1, 2, 3, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
a = [
    [[1,2,3],
    [5,6,7],
    [1,2,3]],
     [[1,2,3],
    [5,6,7],
    [1,2,3]],
     [[1,2,3],
    [5,6,7],
    [1,2,3]]
]
np.pad(a,((0,0),(2,2),(2,2)),mode="constant",constant_values=(0,0))

array([[[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 2, 3, 0, 0],
        [0, 0, 5, 6, 7, 0, 0],
        [0, 0, 1, 2, 3, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 2, 3, 0, 0],
        [0, 0, 5, 6, 7, 0, 0],
        [0, 0, 1, 2, 3, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 2, 3, 0, 0],
        [0, 0, 5, 6, 7, 0, 0],
        [0, 0, 1, 2, 3, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]])

In [11]:
A_prev = np.random.randn(2, 5, 7, 4)
W = np.random.randn(3, 3, 4, 8)

In [12]:
A_prev.shape,W.shape

((2, 5, 7, 4), (3, 3, 4, 8))